# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Delites Codeschnipsel
email: delitecake@gmail.com
description: Hier findet ihr allerhand Tutorials rundums Programmieren von Adopages, Staffelpages usw. Wir benutzen dafür Ruby on Rails. Die Tutorials sind in deutsch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://delitecake.github.io" # the base hostname & protocol for your site
twitter_username: Delite_cake
github_username:  Delitecake

# Build settings
markdown: kramdown
